pipeline {
    agent any
    tools {
      maven 'Maven 3.8.6'
      jdk 'Java 17'
    }
    stages {
        stage("Build") {
            steps {
                sh "mvn clean package"
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
        stage {
            steps {
                echo 'Job completed'
            }
        }
    }
}
